### ISSUE TITLE
Do vecscreen and sourpurge have similar functions?

### ISSUE THREAD

**Issue by maruiqi0710** [stajichlab/AAFTF#22]
Do they all aim to remove contaminants from contigs (i.e., eliminate contigs that do not belong to the target species)?

**Comment by hyphaltip** [comment]
Vecscreen removes primer and obvious contam (phiX) from reads before assembly. 

Sourpurge screens scaffolds for contamination by looking for matches to groups outside the phylum. 

I have also just written in support for NCBI fcs-Gx tool which does similar thing to sourmash/sourpurge step.

**Comment by maruiqi0710** [comment]
In addition to vecscreen and sourpurge, the filter function is also involved in removing gene fragments of non-target species. The filter step removes reads before the assemble step, and also removes reads of mitochondrial genes from the mito step. Therefore, in AAFTF, there are three steps involved in removing gene fragments of non-target species.

Did I summarize it correctly?

**Comment by hyphaltip** [comment]
yes 
- filter is for reads uses BBMap by default against a contamination and primer/adaptor database. It can also be given a set of accessions to screen against if you have known contamination you want to remove at the read level.
- vecscreen is for assembled contigs - this is probably going to be replaced with the [ncbi fcs-adaptor](https://github.com/ncbi/fcs/wiki/FCS-adaptor) step - it recapitulated a vector screening tool that was at ncbi online https://www.ncbi.nlm.nih.gov/tools/vecscreen/ - this step will remove parts or whole contigs that match a vector and adaptor database - if a vector match is found within a contig the contig is split into pieces since one cannot be sure the linkage of the contig is sound now.
- sourpurge is looking for cross-species contamination and removes the entire contig if it is classified as contamination. this is may be subsituted with [ncbi fcs-gx](https://github.com/ncbi/fcs/wiki/FCS-GX)

**Comment by hyphaltip** [comment]
fcs-gx support is now in AAFTF - available in live code and will be part of the v0.5.0 release

**Comment by hyphaltip** [comment]
0.5.0 has these features. closing this query since answered above.
